### ISSUE TITLE
what's the dataset you use?

### ISSUE THREAD

**Issue by YantianZha** [stevenwudi/CVPR_2014_code#3]
You mentioned some datasets in your 2014 CVPR paper. That said, could you provide a link to the dataset you used for this repo? Thanks!

**Comment by stevenwudi** [comment]
Hi, I have updated the links for the datasets used  in the **readme** file. If there is any problem, let me know. Thank you for your interests in my works.

**Comment by YantianZha** [comment]
Thank you!


________________________________
